language: python

python: "3.6.4"

before_install:
  - sudo apt install libudev-dev -y
  - mv travis_secrets.yaml secrets.yaml

addons:
  apt:
    update: true

install:
  - pip3 install homeassistant
  - pip3 install colorlog

script:
  - hass -c . --script check_config --info all
