language: python
python:
  - "3.6"
before_install:
  - sed -i 's/^stream:/#stream:/g' configuration.yaml
  - mv travis_secrets.yaml secrets.yaml
install:
  - pip3 install homeassistant
script:
  - hass -c . --script check_config --info all
