language: python

python: "3.6.4"

before_install:
  - sed -i 's/^stream:/#stream:/g' configuration.yaml
  - rm -f ./packages/stream.yaml
  - mv travis_secrets.yaml secrets.yaml

install:
  - pip3 install homeassistant
  - pip3 install colorlog

script:
  - hass -c . --script check_config --info all
