homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret homeassistant_lat
  longitude: !secret homeassistant_long
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret homeassistant_elev
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Denver
  packages: !include_dir_named packages
  customize: !include customize.yaml

# Enables the frontend
frontend:

panel_custom:
  - name: floorplan
    sidebar_title: Floorplan View
    sidebar_icon: mdi:security-home
    url_path: floorplan
    config: !include floorplan.yaml

# Enables configuration UI
config:

http:
  # Uncomment this to add a password (recommended!)
  # api_password: PASSWORD
  # Uncomment this if you are using SSL or running in Docker etc
  # base_url: example.duckdns.org:8123

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  include_used_components: true

# Discover some devices automatically
discovery:
  ignore:
    - apple_tv
    - axis
    - denonavr
    - directv
    - ikea_tradfri
    - logitech_mediaserver
    - openhome
    - panasonic_viera
    - philips_hue
    - plex_mediaserver
    - roku
    - samsung_tv
    - sonos
    - yamaha
    - yeelight

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

mqtt:

# View all events in a logbook
logbook:
#  exclude:
#    entities:
#      -
# Track the sun
sun:

zoneminder:
  host: 192.168.1.175

# KODI Support
media_player:
  - platform: kodi
    host: 192.168.1.155

  - platform: cast


# Text to speech
tts:
  platform: google

# Load Belkin Wemo devices
wemo:

# Ecobee integration
ecobee:
  api_key: !secret ecobee_key

climate:
  - platform: ecobee

# Z-Wave hub
zwave:
  usb_path: /dev/zwave

python_script:

#logger:
#  default: info

telegram_bot:
  - platform: polling
    api_key: !secret telegram_key
    allowed_chat_ids:
      - !secret telegram_id

notify:
  - name: Telegram
    platform: telegram
    chat_id: !secret telegram_id

#notify:
#  - name: pushbullet
#    platform: pushbullet
#    api_key: !secret pushbullet_key

group: !include_dir_merge_named groups
automation: !include_dir_merge_list automation
script: !include scripts.yaml
device_tracker: !include_dir_merge_list device_trackers
sensor: !include_dir_merge_list sensors
scene: !include_dir_merge_list scenes
input_boolean: !include_dir_merge_named input_booleans
switch: !include_dir_merge_list switches

