homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret homeassistant_lat
  longitude: !secret homeassistant_long
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret homeassistant_elev
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Denver

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  # Uncomment this to add a password (recommended!)
  # api_password: PASSWORD
  # Uncomment this if you are using SSL or running in Docker etc
  # base_url: example.duckdns.org:8123

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  include_used_components: true

# Discover some devices automatically
discovery:
  ignore:
    - apple_tv
    - axis
    - denonavr
    - directv
    - ikea_tradfri
    - logitech_mediaserver
    - openhome
    - panasonic_viera
    - philips_hue
    - plex_mediaserver
    - roku
    - samsung_tv
    - sonos
    - yamaha
    - yeelight

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

#zoneminder:
#  host: 192.168.1.175

# KODI Support
media_player:
  - platform: kodi
    host: 192.168.1.155

  - platform: cast

sensor:
# Weather Prediction
  - platform: darksky
    api_key: !secret darksky_key
    monitored_conditions:
     - summary
     - temperature
     - ozone
  
#  - platform: zoneminder

#  - platform: yr
#    name: "Local Climate"
#    monitored_conditions:
#      - temperature
#      - symbol
#      - precipitation
#  - platform: random
#    name: "random"
#  - platform: time_date
#    name: "timer"
#    display_options:
#      - 'time'
#      - 'date'
#      - 'date_time'
#      - 'time_date'
#      - 'time_utc'
#      - 'beat'

#switch:
#  - platform: zoneminder
#    command_on: Modect
#    command_off: None

# Text to speech
tts:
  platform: google

# Load Belkin Wemo devices
wemo:

# Ecobee integration
ecobee:
  api_key: !secret ecobee_key

climate:
  - platform: ecobee

# Z-Wave hub
zwave:
  usb_path: /dev/zwave

device_tracker:
  - platform: netgear
    host: 192.168.1.1
    username: !secret netgear_user
    password: !secret netgear_pass
    interval_seconds: 30
    consider_home: 180
    track_new_devices: no

notify:
  - name: pushbullet
    platform: pushbullet
    api_key: o.MmHratC9lK2NIxclz5wMmWzqXBEiPeWW

group: !include_dir_merge_named groups
automation: !include_dir_merge_list automation
script: !include scripts.yaml
#script: !include_dir_merge_list script
