homeassistant:
  name: Home
  latitude: !secret homeassistant_lat
  longitude: !secret homeassistant_long
  elevation: !secret homeassistant_elev
  unit_system: imperial
  time_zone: America/Denver
  packages: !include_dir_named packages
  customize: !include customize.yaml

# Enables the frontend
frontend:
  themes: !include_dir_merge_named themes/

# Enables configuration UI
config:

system_health:

mobile_app:

weather:
  - platform: darksky
    api_key: !secret darksky_key
    
http:
  base_url: !secret homeassistant_url 
  ssl_certificate: !secret ssl_cert 
  ssl_key: !secret ssl_key
  ip_ban_enabled: true
  login_attempts_threshold: 3 

# Checks for available updates
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  include_used_components: true

# Discover some devices automatically
discovery:
  ignore:
    - apple_tv
    - axis
    - denonavr
    - directv
    - ikea_tradfri
    - logitech_mediaserver
    - openhome
    - panasonic_viera
    - philips_hue
    - roku
    - samsung_tv
    - yamaha
    - yeelight
    - plex_mediaserver

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

mqtt:
  broker: !secret mqtt_broker 
  port: !secret mqtt_port 


# View all events in a logbook
logbook:

# Track the sun
sun:

alarm_control_panel:
  - platform: manual
    code: !secret alarm_code
    delay_time: !secret alarm_delay_time
    pending_time: !secret alarm_pending_time
    trigger_time: !secret alarm_trigger_time 


# Text to speech
tts:
  platform: google_translate

map:

# Load Belkin Wemo devices
wemo:

# Ecobee integration
ecobee:
  api_key: !secret ecobee_key

# tuya integration
tuya:
  username: !secret tuya_user
  password: !secret tuya_pass
  country_code: 1

# Rachio component
rachio:
    api_key: !secret rachio_api

climate:
  - platform: ecobee

# Z-Wave hub
zwave:
  usb_path: /dev/zwave
  network_key: !secret zwave_key

python_script:

telegram_bot:
  - platform: polling
    api_key: !secret telegram_key
    allowed_chat_ids:
      - !secret telegram_id

notify:
  - name: Push
    platform: html5

  - name: Telegram
    platform: telegram
    chat_id: !secret telegram_id

    #ifttt:
    #  key: !secret ifttt_key

dyson:
    username: !secret dyson_username 
    password: !secret dyson_pass 
    language: US
    devices:
      - device_id: !secret dyson_bedroom_id 
        device_ip: !secret dyson_bedroom_ip 

eufy:
    username: !secret eufy_user
    password: !secret eufy_pass

speedtestdotnet:
  scan_interval:
    minutes: 33
    hours: 6
  monitored_conditions:
    - download
    - upload
    - ping

pi_hole:
  host: !secret pihole_host 
  location: !secret pihole_location
  verify_ssl: true

zone: !include_dir_merge_list zones
light: !include_dir_merge_list lights
input_boolean: !include_dir_merge_named input_booleans
input_select: !include_dir_merge_named input_select
group: !include_dir_merge_named groups
automation: !include_dir_merge_list automation
script: !include scripts.yaml
device_tracker: !include_dir_merge_list device_trackers
sensor: !include_dir_merge_list sensors
#scene: !include_dir_merge_list scenes
switch: !include_dir_merge_list switches
binary_sensor: !include_dir_merge_list binary_sensors
cover: !include_dir_merge_list covers
camera: !include_dir_merge_list cameras


