homeassistant:
  name: Home
  latitude: !secret homeassistant_lat
  longitude: !secret homeassistant_long
  elevation: !secret homeassistant_elev
  unit_system: imperial
  time_zone: America/Denver
  packages: !include_dir_named packages
  customize: !include customize.yaml

# Enables the frontend
frontend:
  themes: !include_dir_merge_named themes/

panel_custom:
  - name: floorplan
    sidebar_title: Floorplan View
    sidebar_icon: mdi:security-home
    url_path: floorplan
    config: !include floorplan.yaml

# Enables configuration UI
config:

panel_iframe:
  router:
    title: 'Dashboard'
    url: 'https://sam-wright.duckdns.org/local/dashboard.html'
    icon: mdi:view-dashboard

http:
  api_password: !secret homeassistant_pass
  cors_allowed_origins:
    - https://sam-wright.duckdns.org


  base_url: sam-wright.duckdns.org
  ssl_certificate: !secret ssl_cert 
  ssl_key: !secret ssl_key
  ip_ban_enabled: true
  login_attempts_threshold: 3 

# Checks for available updates
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  include_used_components: true

# Discover some devices automatically
discovery:
  ignore:
    - apple_tv
    - axis
    - denonavr
    - directv
    - ikea_tradfri
    - logitech_mediaserver
    - openhome
    - panasonic_viera
    - philips_hue
    - roku
    - samsung_tv
    - sonos
    - yamaha
    - yeelight

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

mqtt:
  broker: !secret mqtt_broker 
  port: !secret mqtt_port 


# View all events in a logbook
logbook:
#  exclude:
#    entities:
#      -
# Track the sun
sun:

zoneminder:
  host: !secret zoneminder_address 

# KODI Support
media_player:
  - platform: cast
#   - platform: kodi


# Text to speech
tts:
  platform: google

# Load Belkin Wemo devices
wemo:

# Ecobee integration
ecobee:
  api_key: !secret ecobee_key

climate:
  - platform: ecobee

# Z-Wave hub
zwave:
  usb_path: /dev/zwave
  network_key: !secret zwave_key

python_script:

telegram_bot:
  - platform: polling
    api_key: !secret telegram_key
    allowed_chat_ids:
      - !secret telegram_id

notify:
  - name: Push
    platform: html5

  - name: Telegram
    platform: telegram
    chat_id: !secret telegram_id

#notify:
#  - name: pushbullet
#    platform: pushbullet
#    api_key: !secret pushbullet_key

# scene:
#   - name: Morning
#     entities:
#       light.kitchen_accent_lights: on
#   
#   - name: Day
#     entities:
#       light.kitchen_accent_lights: on
# 
#   - name: Sundown
#     entities:
#       light.kitchen_accent_lights: on
# 
#   - name: Evening
#     entities:
#       light.kitchen_accent_lights: on
#   
#   - name: Sleep
#     entities:
#       light.kitchen_accent_lights: on


ifttt:
  key: !secret ifttt_key

zone: !include_dir_merge_list zones
light: !include_dir_merge_list lights
input_boolean: !include_dir_merge_named input_booleans
input_select: !include_dir_merge_named input_select
group: !include_dir_merge_named groups
automation: !include_dir_merge_list automation
script: !include scripts.yaml
device_tracker: !include_dir_merge_list device_trackers
sensor: !include_dir_merge_list sensors
#scene: !include_dir_merge_list scenes
switch: !include_dir_merge_list switches
binary_sensor: !include_dir_merge_list binary_sensors
cover: !include_dir_merge_list covers


