homeassistant:
  name: Home
  latitude: !secret homeassistant_lat
  longitude: !secret homeassistant_long
  elevation: !secret homeassistant_elev
  unit_system: imperial
  time_zone: America/Denver
  packages: !include_dir_named packages
  customize: !include customize.yaml

# Enables the frontend
frontend:

panel_custom:
  - name: floorplan
    sidebar_title: Floorplan View
    sidebar_icon: mdi:security-home
    url_path: floorplan
    config: !include floorplan.yaml

# Enables configuration UI
config:

http:
  api_password: !secret homeassistant_pass
  # Uncomment this if you are using SSL or running in Docker etc
  base_url: sam-wright.duckdns.org
  ssl_certificate: /etc/letsencrypt/live/sam-wright.duckdns.org/fullchain.pem
  ssl_key: /etc/letsencrypt/live/sam-wright.duckdns.org/privkey.pem
  ip_ban_enabled: true
  login_attempts_threshold: 3 

# Checks for available updates
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  include_used_components: true

# Discover some devices automatically
discovery:
  ignore:
    - apple_tv
    - axis
    - denonavr
    - directv
    - ikea_tradfri
    - logitech_mediaserver
    - openhome
    - panasonic_viera
    - philips_hue
    - roku
    - samsung_tv
    - sonos
    - yamaha
    - yeelight

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

mqtt:

# View all events in a logbook
logbook:
#  exclude:
#    entities:
#      -
# Track the sun
sun:

zoneminder:
  host: !secret zoneminder_address 

# KODI Support
media_player:
  - platform: cast
#   - platform: kodi


# Text to speech
tts:
  platform: google

# Load Belkin Wemo devices
wemo:

# Ecobee integration
ecobee:
  api_key: !secret ecobee_key

climate:
  - platform: ecobee

# Z-Wave hub
zwave:
  usb_path: /dev/zwave

python_script:

telegram_bot:
  - platform: polling
    api_key: !secret telegram_key
    allowed_chat_ids:
      - !secret telegram_id

notify:
  - name: Telegram
    platform: telegram
    chat_id: !secret telegram_id

#notify:
#  - name: pushbullet
#    platform: pushbullet
#    api_key: !secret pushbullet_key

light:
  - platform: mqtt
    name: "Kitchen Accent Lights"
    command_topic: "kitchen/accent/light/switch"
    state_topic: "kitchen/accent/light/status"
    brightness_state_topic: "kitchen/accent/brightness/status"
    brightness_command_topic: "kitchen/accent/brightness/set"
    optimistic: false
    retain: true

input_boolean: !include_dir_merge_named input_booleans
input_select: !include_dir_merge_named input_select
group: !include_dir_merge_named groups
automation: !include_dir_merge_list automation
script: !include scripts.yaml
device_tracker: !include_dir_merge_list device_trackers
sensor: !include_dir_merge_list sensors
scene: !include_dir_merge_list scenes
switch: !include_dir_merge_list switches
binary_sensor: !include_dir_merge_list binary_sensors


