homeassistant:
  name: Home
  latitude: !secret homeassistant_lat
  longitude: !secret homeassistant_long
  elevation: !secret homeassistant_elev
  unit_system: imperial
  time_zone: America/Denver
  packages: !include_dir_named packages
  customize: !include customize.yaml

# Enables the frontend
frontend:

panel_custom:
  - name: floorplan
    sidebar_title: Floorplan View
    sidebar_icon: mdi:security-home
    url_path: floorplan
    config: !include floorplan.yaml

# Enables configuration UI
config:

http:
  api_password: !secret homeassistant_pass
  # Uncomment this if you are using SSL or running in Docker etc
  #base_url: sam-wright.duckdns.org:8123
  #ssl_certificate: !secret ssl_cert
  #ssl_key: !secret ssl_key
  #ip_ban_enabled: true
  #login_attempts_threshold: 2
  trusted_networks:
    - ::1
    - 127.0.0.1
    - 192.168.0.0/24

# Checks for available updates
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  include_used_components: true

# Discover some devices automatically
discovery:
  ignore:
    - apple_tv
    - axis
    - denonavr
    - directv
    - ikea_tradfri
    - logitech_mediaserver
    - openhome
    - panasonic_viera
    - philips_hue
    - plex_mediaserver
    - roku
    - samsung_tv
    - sonos
    - yamaha
    - yeelight

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

mqtt:

# View all events in a logbook
logbook:
#  exclude:
#    entities:
#      -
# Track the sun
sun:

zoneminder:
  host: zoneminder.local

# KODI Support
media_player:
  - platform: cast
#   - platform: kodi


# Text to speech
tts:
  platform: google

# Load Belkin Wemo devices
wemo:

# Ecobee integration
ecobee:
  api_key: !secret ecobee_key

climate:
  - platform: ecobee

# Z-Wave hub
zwave:
  usb_path: /dev/zwave

python_script:

telegram_bot:
  - platform: polling
    api_key: !secret telegram_key
    allowed_chat_ids:
      - !secret telegram_id

notify:
  - name: Telegram
    platform: telegram
    chat_id: !secret telegram_id

#notify:
#  - name: pushbullet
#    platform: pushbullet
#    api_key: !secret pushbullet_key

input_boolean: !include_dir_merge_named input_booleans
# input_text: !include_dir_merge_named input_texts
group: !include_dir_merge_named groups
automation: !include_dir_merge_list automation
script: !include scripts.yaml
device_tracker: !include_dir_merge_list device_trackers
sensor: !include_dir_merge_list sensors
scene: !include_dir_merge_list scenes
switch: !include_dir_merge_list switches
binary_sensor: !include_dir_merge_list binary_sensors


