- alias: 'Grow Lights On'
  trigger:
    platform: time
    at: '12:30:00'

  action:
    - service: homeassistant.turn_on
      entity_id: switch.grow_light 

- alias: 'Grow Lights Off'
  trigger:
    platform: time
    at: '20:00:00'

  action:
    - service: homeassistant.turn_off
      entity_id: switch.grow_light 
