- alias: 'Home Occupancy - Leaving'
  trigger:
    platform: state 
    entity_id: group.family
    to: 'not_home'

  condition:
    condition: state
    entity_id: input_boolean.guest_mode
    state: 'off'

  action:
    - service: climate.set_away_mode
      data:
        away_mode: 'on'
    
    - service: notify.telegram
      data:
        message: 'Home is Empty! Setting Ecobee to _Away_'
        title: 'HomeAssistant Notification'


- alias: 'Home Occupancy - Arriving'
  trigger:
    platform: state 
    entity_id: group.family
    to: 'home'

  action:
    - service: climate.set_away_mode
      data:
        away_mode: 'off'

    - service: notify.telegram
      data:
        title: 'HomeAssistant Notification'
        message: >
            {% if is_state('device_tracker.google_maps_105538345093897058433', 'home') %}
              *Sam* has returned, 
            {% endif %}
            {% if is_state('device_tracker.google_maps_109866597080310477669', 'home') %}
              *Rachel* has returned, 
            {% endif %}
            Setting Ecobee to _Home_
