- alias: 'Morning-on'
  trigger:
    platform: time
    at: '06:30:00'

  action:
    - service: homeassistant.turn_on
      entity_id: light.kitchen_accent_lights 

- alias: 'Morning-off'
  trigger:
    platform: time
    at: '08:30:00'

  action:
    - service: homeassistant.turn_off
      entity_id: light.kitchen_accent_lights 
   

  
