- alias: MQTT Initialize 

  trigger:
    - platform: homeassistant
      event: start
  action:
    - service: mqtt.publish
      data: 
        topic: "garage/door/1/action"
        payload: "STATE"

    - service: mqtt.publish
      data: 
        topic: "cmnd/sonoff/power"
        payload: ""

