- alias: 'Security (Occupancy)'
  trigger:
    - platform: state
      entity_id: group.occupancy
      to: "on"

  condition:
    - condition: state
      entity_id: group.family
      state: "away"

  action:
    service: notify.telegram
    data: 
      message: "Motion Detected!"
      title: "HomeAssistant Alert!"

  
