- alias: 'Sleep'
  trigger:
    platform: time
    at: '00:30:00'

  action:
    - service: homeassistant.turn_off
      entity_id: switch.bedroom_lamp 
    - service: homeassistant.turn_off
      entity_id: switch.downstairs_bedroom_lamp 
    #- service: homeassistant.turn_off
    #  entity_id: switch.tree_lights
   

  
