- alias: 'Sleep'
  trigger:
    platform: time
    at: '00:30:00'

  action:
    - service: homeassistant.turn_off
      entity_id: switch.bedroom_lamp_rachel 
    - service: homeassistant.turn_off
      entity_id: switch.bedroom_lamp_sam 
    - service: homeassistant.turn_off
      entity_id: switch.downstairs_bedroom_lamp
    - service: homeassistant.turn_off
      entity_id: light.kitchen_accent_lights
    - service: homeassistant.turn_off
      entity_id: switch.porch_light_switch
    - service: homeassistant.turn_off
      entity_id: switch.front_room_switch
    - service: homeassistant.turn_off
      entity_id: switch.front_room_lamp
    - service: homeassistant.turn_off
      entity_id: switch.bedroom_lamp_sam
    - service: homeassistant.turn_off
      entity_id: switch.bedroom_lamp_rachel
    - service: homeassistant.turn_off
      entity_id: switch.downstairs_bedroom_lamp 
   
- alias: 'AutoSleep'
  trigger:
    - platform: template
      value_template: "{{ state_attr('device_tracker.google_maps_105538345093897058433', 'battery_charging') }}"
    - platform: template
      value_template: "{{ state_attr('device_tracker.google_maps_109866597080310477669', 'battery_charging') }}"

  condition:
    condition: and
    conditions:
      - condition: template
        value_template: "{{ state_attr('device_tracker.google_maps_105538345093897058433', 'battery_charging') }}"
      - condition: template
        value_template: "{{ state_attr('device_tracker.google_maps_109866597080310477669', 'battery_charging') }}"
      - condition: template
        value_template: "{{ is_state('device_tracker.google_maps_105538345093897058433','home') }}"
      - condition: template
        value_template: "{{ is_state('device_tracker.google_maps_109866597080310477669','home') }}"
      - condition: time
        before: '3:00:00'
        after: '20:00:00'

  action:
    - service: homeassistant.turn_off
      entity_id: switch.bedroom_lamp_rachel 
    - service: homeassistant.turn_off
      entity_id: switch.bedroom_lamp_sam 
    - service: homeassistant.turn_off
      entity_id: switch.downstairs_bedroom_lamp
    - service: homeassistant.turn_off
      entity_id: light.kitchen_accent_lights
    - service: homeassistant.turn_off
      entity_id: switch.porch_light_switch
    - service: homeassistant.turn_off
      entity_id: switch.front_room_switch
    - service: homeassistant.turn_off
      entity_id: switch.front_room_lamp
    - service: homeassistant.turn_off
      entity_id: switch.bedroom_lamp_sam
    - service: homeassistant.turn_off
      entity_id: switch.bedroom_lamp_rachel
    - service: homeassistant.turn_off
      entity_id: switch.downstairs_bedroom_lamp 

    
