- alias: 'Sundown'
  trigger:
    platform: sun
    event: sunset
    offset: '00:00:00'
 
  action:
#    - service: homeassistant.turn_on
#      entity_id: switch.tree_lights 
    - service: homeassistant.turn_on
      entity_id: light.kitchen_accent_lights
   

  
