- alias: 'Webcam Notifier'

  trigger:
    - platform: state
      entity_id: sensor.theo_cam_events 
  
  condition: 
    condition: or
    conditions:
      - condition: state
        entity_id: binary_sensor.theo_cam_events_trend 
        state: 'on'
      - condition: state
        entity_id: sensor.theo_cam_status
        state: 'Modect'

  action:
    service: notify.telegram
    data: 
      message: 'Zoneminder: Motion Detected!'
      title: 'HomeAssistant Notification'

- alias: 'Webcam Monitoring On'

  trigger: 
  - platform: time
    at: '00:00'
  
  action:
    - service: homeassistant.turn_on
      entity_id: switch.theo_cam_state 
  
- alias: 'Webcam Monitoring Off'

  trigger: 
  - platform: time
    at: '07:00'

  action:
    - service: homeassistant.turn_off
      entity_id: switch.theo_cam_state
