- alias: 'Webcam Notifier'
  trigger:
    - platform: state
      entity_id: sensor.theo_cam_events

  condition:
    - condition: state
      entity_id: sensor.theo_cam_status
      state: "Modect"
    - condition: numeric_state
      entity_id: sensor.theo_cam_events
      above: 0

  action:
    service: notify.telegram
    data: 
      message: "Zoneminder: Motion Detected!"
      title: "HomeAssistant Notification"

  
