- alias: 'Webcam Notifier'
  trigger:
    - platform: state
      entity_id: binary_sensor.theo_cam_events_trend 
      to: 'on'

  action:
    service: notify.telegram
    data: 
      message: "Zoneminder: Motion Detected!"
      title: "HomeAssistant Notification"

  
