- alias: 'Workshop Heat On'
  trigger:
    platform: numeric_state
    entity_id: sensor.vision_zp3111_multisensor_4in1_temperature
    below: 30
  action:
    - service: switch.turn_on 
      entity_id: switch.shop_lights
    - service: notify.telegram
      data:
        message: 'Workshop temp below 30, turning Shop Heat ON' 

- alias: 'Workshop Heat Off'
  trigger:
    platform: numeric_state
    entity_id: sensor.vision_zp3111_multisensor_4in1_temperature
    above: 35
  action:
    - service: switch.turn_off
      entity_id: switch.shop_lights
    - service: notify.telegram
      data:
        message: 'Workshop temp above 35, turning Shop Heat OFF' 

